apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: kfserving-trigger
spec:
  broker: default
  filter:
    attributes:
      type: dev.knative.samples.helloworld
      source: dev.knative.samples/helloworldsource
  subscriber:
    ref:
     apiVersion: serving.kubeflow.org/v1alpha2
     kind: InferenceService
     name: kfserving-custom-model